### ISSUE TITLE
Unable to access dataset

### ISSUE THREAD

**Issue by agaldran** [jeremykawahara/derm7pt#6]
Hi Jeremy,

I am trying to access the data from the website associated to your paper [here](http://derm.cs.sfu.ca/), but after filling out the form twice with my institutional and personal email address (like half an hour ago), I still have not received any email with download instructions. Could you please help me out?

Thanks :)

**Comment by jeremykawahara** [comment]
hi @agaldran thanks for your message - I resent to your institutional address. Please let me know if that works now. Thanks!

**Comment by agaldran** [comment]
Hi, @jeremykawahara , I got the email now, thanks a lot for your quick answer :)
